#!/bin/sh
# File generated by ocamlbuild

cd /home/ultra/Developer/ocaml/hello

rm -f bin/main.cmi
rm -f bin/main.cmo
# Also clean the script itself
rm -f /home/ultra/Developer/ocaml/hello/_build/sanitize.sh
